#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\LoginController::login

api:
    resource: '../src/Controller/'
    type: annotation